"""Add vault documents table

Revision ID: b54f9796e0b6
Revises: 002_remove_subscription_plan
Create Date: 2026-04-16 05:00:16.844040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b54f9796e0b6'
down_revision: Union[str, Sequence[str], None] = '002_remove_subscription_plan'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('admins', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('fingerprints', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('fingerprints', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('fingerprints', 'is_trusted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_fingerprints_hash'), table_name='fingerprints')
    op.create_index(op.f('ix_fingerprints_fingerprint_hash'), 'fingerprints', ['fingerprint_hash'], unique=True)
    op.drop_constraint(op.f('fingerprints_user_id_fkey'), 'fingerprints', type_='foreignkey')
    op.create_foreign_key(None, 'fingerprints', 'users', ['user_id'], ['id'])
    op.alter_column('members', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('partners', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('partners', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.create_unique_constraint(None, 'sessions', ['token'])
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(None, 'sessions', type_='unique')
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.alter_column('sessions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('partners', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('partners', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('members', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'fingerprints', type_='foreignkey')
    op.create_foreign_key(op.f('fingerprints_user_id_fkey'), 'fingerprints', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_fingerprints_fingerprint_hash'), table_name='fingerprints')
    op.create_index(op.f('ix_fingerprints_hash'), 'fingerprints', ['fingerprint_hash'], unique=True)
    op.alter_column('fingerprints', 'is_trusted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('fingerprints', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('fingerprints', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('admins', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('admins', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
